;********************************************************
;       IT graphlib globals                             *
;********************************************************
	.global	ImageBank
	.global	CModeFlag
	.global	PixelMask
	.global	BQFront
	.global	BQEnd
	.global	AQStat          
	.global	window_x
	.global	window_y
	.global	wind_wid
	.global	wind_hgt

        
	.global	Blit            ;routines
	.global	DoVint
	.global	DoView
	.global	DoEnable
	.global	waitblitter
	.global	LoadPalette
	.global	DoNextCmd
