checksum grom00_0.bin >rad.txt
checksum grom00_1.bin >>rad.txt
checksum grom00_2.bin >>rad.txt
checksum grom00_3.bin >>rad.txt

checksum grom01_0.bin >>rad.txt
checksum grom01_1.bin >>rad.txt
checksum grom01_2.bin >>rad.txt
checksum grom01_3.bin >>rad.txt

checksum grom02_0.bin >>rad.txt
checksum grom02_1.bin >>rad.txt
checksum grom02_2.bin >>rad.txt
checksum grom02_3.bin >>rad.txt

checksum grom03_0.bin >>rad.txt
checksum grom03_1.bin >>rad.txt
checksum grom03_2.bin >>rad.txt
checksum grom03_3.bin >>rad.txt
